# Stochastic Calculus {#stoch}

-   Brownian motion & its properties
    -   Example: $Y(t)=W(t)^2-t$
    -   Exponential martingale
-   Ito's Lemma
-   Martingale process: drift term = 0
    -   Stoch models assignment 7 1.a
-   Ornstein-Uhlenbeck process: how to get its solution
    -   see diff eq?
    -   relate to stoch models
-   Wald's martingale
-   Gambler's ruin






-   brownian motion
    -   lecture 1, 2
    -   relate to other courses
    -   discrete time random walk motivation
        -   description
        -   drawbacks
    -   list of conditions that need to hold
        -   check these properties for other processes (not just W_t)
        -   examples?
    -   lim property of differentiation (proof)
    -   motivation for continuous time
        -   vs discrete time

-   probability space
    -   definition
    -   omega - sample space (relate to prob theory) of exhaustive (mutually exclusive) things that could happen
    -   F - sigma algebra - collection of subsets of omega st certain set conditions hold
    -   P - probability space - maps F to 0, 1 again with some conditions

-   filtration
    -   applied on a probability space
    -   describes how information evolves over time
    -   do the notation
    -   definition: family of sigma fields (all F_t for t\>=0)
    -   application: often filtration is chosen to be info generated over time is generated by a brownian motion

-   stochastic differential equations (SDE)
    -   lecture 3
    -   example: population growth model
        -   chose to model population growth of unknown starting size with a constant drift term and random component
        -   two random components
            -   initial starting
            -   noise term
    -   formal form
        -   $dX_t=\mu\left(t,X_t\right)dt+\sigma\left(t,X_t\right)dW_t,\ \ \ \ \ \ \ \ X_0=X_0\left(\omega\right)$
        -   change = deterministic part (drift) + diffusion part

-   diffusion process
    -   solution of SDE is called a diffusion process X_t (aka diffusion process satisfies the SDE)
    -   usually X_0 known in financial applications (ex. starting stock price)
    -   continuity of a diffusion process
        -   definition: all sample paths/trajectories are continuous
        -   continuous for all outcomes
        -   look up shreve, point?
    -   strong solution to SDE is diffusion process X_t st:
        -   why do we want this?
        -   X_t continuous
        -   prob starting point = X\^o =1
        -   integral of abs val of drift & diffusion parts \< infty wp 1 (what is this called & why)
        -   X_t a function of X_0, integral drift, and integral diffusion (see stochastic integral)

-   quadratic variation
    -   lecture 3
    -   used in stoch integrals
    -   refer to shreve
    -   def: new process defined to be sum of all squared (continuous) original process differences as max partition size goes to zero
    -   if original process is brownian motion, new process goes to T almost surely (see data analysis)
    -   levy's thoerem
        -   super important to link martingales with brownian motions
        -   if M(t) martingale has quad var t, then it's a brownian motion
        -   proof shreve?
        -   used in ito - box calc - dWdW = dt
    -   estimating using realized variance

-   quadratic covariation
    -   lecture 3
    -   similar steps as quadratic var, but with two variables
    -   ultimately results in dWdZ = 0

-   martingales
    -   lecture 3
    - use: 
    -   relate to stoch models
    -   discrete
        -   definitions
            -   filtration in discrete time
            -   measurable
            -   adapted vs. predictable
            -   martingale: adapted, finite mean, conditional expectation is current value
        -   example: total winnings
        -   example: random walk
    -   continuous
        -   definition
        -   submartingale, supermartingale
        -   example: brownian motion is a martingale
            -   expectation finite PROOF
                -   uses properties of squaring and quad var
            -   conditional expectation
                -   separation trick
            -   conclusion: best estimate of future value of BM is its present value

-   stochastic integrals
    -   lecture 4
    - definition: integral with dW
    -   discrete
        -   martingale transform
            - rooted in difference of original martingale
            -   definition: sum of A_k(M_k - M_k-1)
            -   proof it's also a martingale
        -   example: gambling strategy total winnings
    -   continuous
        -   def
        -   square integrable
        -   ito isometry: relates expectation of squared integration of X_t \* dW_t
    -   ito integral
        -   function of process X: I(X)
        -   limit of simple integrals
        - based on discrete partitions
        -   see shreve?
        -   example: ito integral of brownian motion
    -   integral process I_t
        -   continuous time version of martingale transform
        -   gives solution to driftless diffusion SDE! PROOF

-   Ito's rule
    - lecture 5
    - use: obtaining dynamics of FUNCTIONS of diffusion processes
        - ex. functions of brownian motions
        - used in girsanov thm
    - one dimensional
        -   SDE where mu and sig functions are adapted
        -   change in function of the diffusion (ito) process is by partials
        -   box calculus (relate to stoch models)
        -   proof: relate to taylor expansion, chain rule, see shreve
    - multidimensional case
        -   all the notation
            - in integral form
        -   do for n = 2
        -   correlated brownian motions
        -   example Z=XY, product of two 2-d BMs

-   change of measure
    - lecture 5
    - motivation: alter the dynamics of SDE to make process (discounted asset prices) a martingale. then expectation of that should be price today by def of martingale
    -   setup: define new P\~ in terms of a RV and P
    -   P\~ is prob measure (why? go to def of prob measure)
    -   properties of expectations of rvs
        - see shreve?
        - relate prob to expectation of indicator to integral
    -   density - map between ???
    -   absolutely continuity
        -   consistency condition between two measures
    - lecture 6
    -   radon-nikodym theorem
        -   unique and guaranteed map between measures
        -   proof?
    - example: normal rv
        -   get used to notation
            -   $A$ is some outcome for standard normal RV $\xi$
                -   for example $A$ could be the interval [3,5] in the real number line
        -   define some function $\mu$ given $\xi$ and $A$ to be the probability that $\xi$ is in $A$
            -   $\mu_{\xi}\left(A\right):=\mathbb{P}\left(\xi\in A\right)=\int_A\frac{1}{\sqrt{2\pi}}e^{\frac{x^2}{2}}$
        -   define $\xi^\prime=a+\xi$
        -   give prob xi_prime in A
        -   create the ratio of the infinitesimal changes in the two probabilities
            -   this is the ratio of densities
        -   define P\~ based off this ratio
            -   dP~/dP
            -   it is a random variable in terms of xi_prime
            -   is it based off of integral representation of expectations?
            -   by the definition of xi_prime can rewrite in terms of xi
        -   check
            -   expectation for func of xi_prime under P~ == expectation of func of xi under P
        -   relate to simulation likelihood ratio?
    - example: discrete time multiple normal rv
        - iid assumption
        - similar setup to single, except vector notation and a's allowed to be time varying *predictable* processes
        - expectation for function of RVs
            - repeated product of densities b/c iid assumption
        - blah blah: jacobian lower triangular, determinant prod of diag - how is this used to come up with the following?
        - end up with dP~/dP similar to univariate case
        - why doesn't work if a's are *adapted*?

- girsanov theorem
    -   Lecture 7
    -   continuous time application of prev multi-d example
    -   use: get rid of drift term on brownian motion where drift is adapted process
    -   definition
        - Z is the function that changes measure
        - relate new measure to expectation of indicator
    -   novikov condition
        -   why? ensure expectation of Z = 1
    -   proof for 1-d
    -   example: risk-neutral pricing
        -   GBM
        -   define F_t
            -   it's the radon-nikodym deriv used to go from P to P~
            -   defined first for arbitrary kappa, then set kappa to r
        -   forces e-rt S_t to be a martingale

-   martingale representation theorem
    - lecture 8
    -   use: no arbitrage replication proof
    -   definition: every martingale can be represented as ito integral... blah blah

-   univariate pricing by no arbitrage
    - lecture 8
    -   definition of replication
        - ex. single period
        - lecture 9
        - ex. continuous time
    -   connection with risk neutral probabilities
        - lecture 10
        -   relate to foundations of FE
        -   market price of risk - is there relation to sharpe or implied vol class?

-   multidimensional market model
    - Lecture 10
    - shreve 5.4.2
    - notation & setup
        - m stocks following correlated BMs
        - there's also domestic risk free money market account
        - Z in this case is related to corr matrix
        - get used to number of equations and number of unknowns
        - this is a model, not real life
    - goal is to find P~ such that all discounted stock prices are martingales
    - lecture 11
    - careful definition of radon-nikodym deriv
    - use of levy's theorem
    - example: m=2
        - solve mpr equations for theta
        - two equations, one unknown
        - again relate to implied vol class?
    - first fundamental theorem of asset pricing
        - lecture 12
        - definition: if multi-d market model has risk-neutral prob measure, it does not admit an arbitrage (i.e. the mpr equations can be solved) PROOF
        - example HJM model (relate to term structure)
            - application of first fundamental thm - prevent arbitrage across term structure
            - requires leibnitz rule
            - lecture 12, 13
            - shreve 10.3
            - relate to term-structure & foundations
            - models forward curve
            - what are the steps and why?
            - ultimately end up with HJM condition, which imposes a relation between drift and vol of forward rate if there's not to be arbitrage
    - market completeness (second fundamental theorem of asset pricing)
        - lecture 14
        - shreve 5.4.4
        - definition: multi-d market model complete if any contingent claim can be replicated or hedged with existing markets
        - uses martinagle representation theorem
        - requires that risk-neutral measure is unique
        - see A matrix - needs to of rank d, invertible?
        - hedging equations

-   partial differential equations
    -   lecture 15, shreve chap 6
    - theorems for function of SDE (not just BM)
    -   blah blah
    - defines special functions (g & f- discounted) of terminal condition and applies itos lemma?
    -   feynman-kac
        -   one dimensional
            -   example: black scholes
                - derives a PDE from terminal condition and SDEs
                - check for market completeness
        -   multi dimensional
            - lecture 16
            - payoff function of multiple stochastic processes
            - multi-d feynman-kac & multi-d discounted-feynman-kac
            - ex. heston model, lecture 17, 18
                - derive PDE from multi-d feynman kac
                - ultimately want options pricing
                    - stochastic vol
                    - quadratic variance
                    - change of measure
                    - girsanov
                - market model is incomplete b/c there's more sources of risk than tradeable assets (what's the implication)
            -   ex. asian option (relate to foundations of FE and simulation)
                - lecture 18
                - shreve 7.5
                - relate to simulation asian options
                - careful definition of cumulative stock price process
                - stuff it into the 2-d feynman kac formula
                - additionally derive the delta of the asian option

- change of numeraire
    - lecture 19, 20
    - Shreve 9.2.1
    - HW 5
    - point? FX?
    - relation to change of measure
    - how does it fit into the market model?
    - example1 : multi-d market model
        - many risk assets with domestic money market account
        - re-derive dynamics of a stock choosing another stock as the numeraire
    - example 2: forward measures
        - shreve 9.4
        - lecture 20, 21
        - application: option pricing with stochastic interest rates
        - numeraire set to ZCB opposed to money market account
    - example 3: FX model
        - lecture 21
        - shreve 9.3
        - this is a 1-d market model where there's 
            - domestic money market account
            - foreign money market account
            - risk asset denominated in domestic currency
            - there is process Q, the exchange rate process
        - show that all discounted security prices are martingales when foreign MM account chosen as numeraire
        - ex. quanto option
            - lecture 22 & homework
            - change of measure done in class
    - foreign exchange model
        - lecture 23
        - instead of market model, we have a series of crosses
        - point is to write S(1) as martingale?
        
- exotic options
    - in class, allow for vol to be any adapted process
    - ex. barrier option
        - lecture 23, 24
        - shreve chapter 7 for GBM
        - price by replication
        - up and in (relate to implied vol, comp methods?)
        - split into cases of hitting barrier
    - ex. lookback option
        - lecture 24, 25
        - define special process for window max
        - derive pde and boundary conditions
        - also get delta hedging strategy (recall why this is important for replication)

- continuous time portfolio optimization
    -   relate to dynamic programming
    -   Lecture 25-27
    -   Cvitanic and Zapatero, Chapter 4.
    -   setup
        - real world proabilities
        - pi strategy of how much to allocate to risk stock (vs. money market account)
        - utility function used to encode investor preference
            - jensen's inequality (relate to calc?)
            - concave utility functions --> risk-averse
                - log
                - power
                - exponential
    - utility maximization in continuous time
        - lecture 26
        - dynamic programming principle
        - choose pi to maximize running utility w
        - admissible markov feedback trading strategy
        - define recursion
        - Hamilton-Jacobi-Bellman (HJB)
    -   optimal portfolio selection
        - consider 1 risk stock and domestic bank account
        - first order condition can be used b/c we know utility is concave?
        - ansatz (relate to diff-eq)
        - consumption occurs at the end
        - example for log utility function
    - utility maximization from consumption
        - investor can consume wealth over each time period
        - changes objective function & HJB equation
